OpenJEVis/JEVis

JEAPI-WS/src/main/java/org/jevis/jeapi/ws/Info.java, JEAPI-WS/src/main/java/org/jevis/jeapi/ws/JEVisAttributeWS.java, JEAPI-WS/src/main/java/org/jevis/jeapi/ws/JEVisDataSourceWS.java, JEAPI-WS/src/main/java/org/jevis/jeapi/ws/JEVisSampleWS.java, JEAPI-WS/src/main/java/org/jevis/jeapi/ws/JEVisUserWS.java, JEApplication/src/main/java/org/jevis/application/application/I18nWS.java, JEApplication/src/main/java/org/jevis/application/login/FXLogin.java, JECommons/src/main/java/org/jevis/commons/application/ApplicationInfo.java, JECommons/src/main/java/org/jevis/commons/unit/JEVisUnitImp.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/JEConfig.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/browser/ISO5001Browser.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/ObjectEditor.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/attribute/BasicEditor.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/attribute/BooleanValueEditor.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/attribute/LanguageEditor.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/attribute/LongEditor.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/extension/GenericAttributeExtension.java, JEWebService/pom.xml, JEWebService/src/main/java/org/jevis/ws/sql/tables/SampleTable.java
Fixed the JEVisSample for long values and made it more save for long double. Also cleaned a lot of debug messages.
=> Double/Long Sampe Fix

JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/attribute/BasicEditor.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/attribute/DoubleEditor.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/attribute/LongEditor.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/attribute/StringEditor.java
Add an empty number validation handling
=> Empty number handling

JEApplication/src/main/java/org/jevis/application/jevistree/JEVisTreeItem.java, JECommons/src/main/java/org/jevis/commons/classes/ClassHelper.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/JEConfig.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/sample/SampleEditor.java
JEVisTree will sort directories above Objects, see #59 . Also removed the Raw Data calculator form the same dialog, see #63
=> JEVisTree sorting

JEApplication/src/main/java/org/jevis/application/dialog/NewObjectDialog.java, var/i18n/Building.json, var/i18n/MonitoredObject.json, var/i18n/MonitoredObjectDirectory.json
Fix to Class translation of Building, Monitored Object and Monitored Object Directory
=> Translated classname not suggested when creating new object #8

JEApplication/src/main/java/org/jevis/application/jevistree/TreeHelper.java, JEApplication/src/main/java/org/jevis/application/tools/CalculationNameFormater.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/extension/calculation/CalculationViewController.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/extension/calculation/FormelBox.java, JEVisControlCenter/src/main/resources/JEVisCC_de.properties, JEVisControlCenter/src/main/resources/JEVisCC_en.properties, JEVisControlCenter/src/main/resources/fxml/EditCalculation.fxml
JECC - Calc editor has no option to select the output data row HIGH PRIORITY
=> Fixed #215

JEApplication/src/main/java/org/jevis/application/Chart/BarChartSerie.java, JEApplication/src/main/java/org/jevis/application/Chart/Charts/BarChart.java, JEApplication/src/main/java/org/jevis/application/Chart/Charts/LineChart.java, JEApplication/src/main/java/org/jevis/application/Chart/Charts/PieChart.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/graph/view/ChartView.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/graph/view/ToolBarView.java
fixed null pointer in pie chart
=> Fixed null pointer in line chart period

JEDataProcessor/src/main/java/org/jevis/jecalc/data/CleanDataAttributeJEVis.java, JEDataProcessor/src/main/java/org/jevis/jecalc/differential/DifferentialStep.java, JEDataProcessor/src/main/java/org/jevis/jecalc/gap/FillGapStep.java, JEDataProcessor/src/main/java/org/jevis/jecalc/limits/LimitsStep.java, JEDataProcessor/src/main/java/org/jevis/jecalc/util/GapsAndLimits.java, JEDataProcessor/src/main/java/org/jevis/jecalc/workflow/ProcessStep.java, pom.xml
=> Fixed problem with average value calculation

JEVisControlCenter/src/main/java/org/jevis/jeconfig/sample/AttributeOptionExtension.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/sample/AttributeStatesExtension.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/sample/AttributeUnitExtention.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/sample/SampleEditor.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/sample/SampleEditorExtension.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/sample/SampleExportExtension.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/sample/SampleGraphExtension.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/sample/SampleTableExtension.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/sample/tableview/SampleTable.java
Add disable function the the sampleeditor extensions.
=> Replaced datepicker in sample editor.

JEApplication/src/main/java/org/jevis/application/Chart/data/GraphDataModel.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/graph/view/GraphPluginView.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/graph/view/ToolBarView.java
Auto chart size will also happen if the screen size changes.
=> Auto chart size is now a toggle button.

JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/graph/view/GraphPluginView.java, JEVisControlCenter/src/main/jnlp/template.vm
Graphs will now check there maximum width.
Fixed an bug where loaded analysis will ignore data based min size.
=> Add href to the JNLP template.

JEVisControlCenter/src/main/java/org/jevis/jeconfig/sample/SampleEditor.java
Add an reload of the attribute if the sample editor starts.
=> Fixed the until date selection.

JEApplication/src/main/java/org/jevis/application/Chart/data/DateHelper.java, JEApplication/src/main/java/org/jevis/application/Chart/data/GraphDataModel.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/graph/LoadAnalysisDialog.java
JECC - Charts - Load Analysis Dialog #359
=> JECC - Charts - Load Analysis Dialog #358

JEApplication/src/main/java/org/jevis/application/Chart/ChartDataModel.java, JEApplication/src/main/java/org/jevis/application/Chart/Charts/AreaChart.java, JEApplication/src/main/java/org/jevis/application/Chart/Charts/BarChart.java, JEApplication/src/main/java/org/jevis/application/Chart/Charts/LineChart.java, JEApplication/src/main/java/org/jevis/application/Chart/Charts/PieChart.java, JEApplication/src/main/java/org/jevis/application/Chart/data/GraphDataModel.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/graph/LoadAnalysisDialog.java
JECC - Diagramme - Zeitfilter chronologisch sortieren #365
=> JECC - Diagramme - "Auswahl abwählen" funktioniert nicht #394

JEAPI-WS/src/main/java/org/jevis/jeapi/ws/JEVisDataSourceWS.java, JEApplication/src/main/java/org/jevis/application/dialog/SelectTargetDialog2.java, JEApplication/src/main/java/org/jevis/application/jevistree/ColumnFactory.java, JEApplication/src/main/java/org/jevis/application/jevistree/JEVisTree.java, JEApplication/src/main/java/org/jevis/application/jevistree/JEVisTreeFactory.java, JEApplication/src/main/java/org/jevis/application/jevistree/JEVisTreeRow.java, JEApplication/src/main/java/org/jevis/application/jevistree/filter/BasicCellFilter.java, JEApplication/src/main/java/org/jevis/application/jevistree/filter/FilterFactory.java, JEApplication/src/main/java/org/jevis/application/jevistree/filter/FilterTreeLoader.java, JEApplication/src/main/java/org/jevis/application/jevistree/filter/JEVisItemLoader.java, JEApplication/src/main/java/org/jevis/application/jevistree/filter/JEVisTreeFilter.java, JEApplication/src/main/java/org/jevis/application/jevistree/filter/ObjectAttributeFilter.java, JEApplication/src/main/java/org/jevis/application/jevistree/filter/TreeItemComparator.java, JEApplication/src/main/java/org/jevis/application/jevistree/plugin/SimpleTargetPlugin.java
Merge branch 'master' of https://github.com/OpenJEVis/JEVis into TreeFilter
#	JEApplication/src/main/java/org/jevis/application/jevistree/JEVisTreeFactory.java
#	JEApplication/src/main/java/org/jevis/application/jevistree/plugin/ChartPlugin.java
=> Fixed bugs in tree.

JEAPI-WS/src/main/java/org/jevis/jeapi/ws/JEVisObjectWS.java, JEApplication/src/main/java/org/jevis/application/dialog/SelectTargetDialog.java, JEApplication/src/main/java/org/jevis/application/jevistree/ColumnFactory.java, JEApplication/src/main/java/org/jevis/application/jevistree/Finder.java, JEApplication/src/main/java/org/jevis/application/jevistree/JEVisTree.java, JEApplication/src/main/java/org/jevis/application/jevistree/JEVisTreeItem.java, JEApplication/src/main/java/org/jevis/application/jevistree/SearchFilterBar.java, JEApplication/src/main/java/org/jevis/application/jevistree/TreeHelper.java, JEApplication/src/main/java/org/jevis/application/jevistree/filter/JEVisItemLoader.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/csv/CSVColumnHeader.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/ObjectPlugin.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/attribute/TargetEditor.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/extension/GenericAttributeExtension.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/extension/RootExtension.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/extension/calculation/FormulaBox.java
May fixed the attribute update bug.
=> Add new search and highlight function for the jevistree.

JEApplication/src/main/java/org/jevis/application/Chart/ChartDataModel.java, JEApplication/src/main/java/org/jevis/application/Chart/ChartPluginElements/AggregationColumn.java, JEApplication/src/main/java/org/jevis/application/Chart/ChartPluginElements/DateColumn.java, JEApplication/src/main/java/org/jevis/application/Chart/ChartPluginElements/SelectionColumn.java, JEApplication/src/main/java/org/jevis/application/Chart/ChartPluginElements/UnitColumn.java, JEApplication/src/main/java/org/jevis/application/Chart/ChartSettings.java, JEApplication/src/main/java/org/jevis/application/Chart/Charts/AreaChart.java, JEApplication/src/main/java/org/jevis/application/Chart/Charts/BarChart.java, JEApplication/src/main/java/org/jevis/application/Chart/Charts/BubbleChart.java, JEApplication/src/main/java/org/jevis/application/Chart/Charts/Chart.java, JEApplication/src/main/java/org/jevis/application/Chart/Charts/LineChart.java, JEApplication/src/main/java/org/jevis/application/Chart/Charts/PieChart.java, JEApplication/src/main/java/org/jevis/application/Chart/Charts/ScatterChart.java, JEApplication/src/main/java/org/jevis/application/Chart/data/GraphDataModel.java, JEApplication/src/main/java/org/jevis/application/dialog/ChartSelectionDialog.java, JEApplication/src/main/java/org/jevis/application/jevistree/plugin/ChartPlugin.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/graph/LoadAnalysisDialog.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/graph/view/ChartView.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/graph/view/GraphExport.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/graph/view/GraphPluginView.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/graph/view/ToolBarView.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/sample/SampleGraphExtension.java, var/templates/jecalc.service, var/templates/jedataprocessor.service, var/templates/jereport.service, var/templates/jewebservice.service, var/templates/log4j2.xml
fixed selection dialog
updated services
=> performance improvements

JEAPI-WS/src/main/java/org/jevis/jeapi/ws/HTTPConnection.java, JEAPI-WS/src/main/java/org/jevis/jeapi/ws/JEVisDataSourceWS.java, JEAPI-WS/src/main/java/org/jevis/jeapi/ws/JEVisObjectWS.java, JEApplication/src/main/java/org/jevis/application/dialog/SelectTargetDialog.java, JEApplication/src/main/java/org/jevis/application/jevistree/filter/BasicCellFilter.java, JEApplication/src/main/java/org/jevis/application/jevistree/filter/FilterFactory.java, JECommons/src/main/java/org/jevis/commons/classes/ClassHelper.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/ObjectPlugin.java
=> Fixed some missing class cache.

JEApplication/src/main/java/org/jevis/application/dialog/SelectTargetDialog.java, JEApplication/src/main/java/org/jevis/application/jevistree/JEVisTree.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/ObjectPlugin.java
=> Add expanse/collapse function to tree.

DataCollector/JEDataCollector/src/main/java/org/jevis/jedatacollector/Launcher.java, JEApplication/src/main/java/org/jevis/application/Chart/ChartDataModel.java, JEApplication/src/main/java/org/jevis/application/Chart/data/GraphDataModel.java, JECalc/src/main/java/org/jevis/jecalc/ServiceMode.java, JECommons/src/main/java/org/jevis/commons/dataprocessing/function/MathFunction.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/ServiceMode.java, JEReport/src/main/java/org/jevis/report3/ServiceMode.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/graph/LoadAnalysisDialog.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/graph/view/GraphPluginView.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/graph/view/ToolBarView.java
fixed job queue id
fixed bug in running mean
=> fixed queue for datacollector

JEApplication/src/main/java/org/jevis/application/dialog/ChartSelectionDialog.java, JEApplication/src/main/java/org/jevis/application/jevistree/JEVisTree.java, JEApplication/src/main/java/org/jevis/application/jevistree/JEVisTreeContextMenu.java, JEApplication/src/main/java/org/jevis/application/jevistree/JEVisTreeFactory.java, JEApplication/src/main/java/org/jevis/application/jevistree/SearchFilterBar.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/JEConfig.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/ObjectPlugin.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/extension/GenericAttributeExtension.java
Add the searchbar to the graph selection.
=> Fixed copy&paste bug where a second paste did not work.

DataCollector/JEDataCollector/src/main/java/org/jevis/jedatacollector/Launcher.java, JECalc/src/main/java/org/jevis/jecalc/CalcLauncher.java, JECommons/src/main/java/org/jevis/commons/cli/AbstractCliApp.java, JECommons/src/main/java/org/jevis/commons/task/LogTaskManager.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/Launcher.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/workflow/ProcessManager.java, JEReport/src/main/java/org/jevis/report3/ReportLauncher.java
adopted dataprocessor task logging table to other services
=> fixes to the service modes

JEDataProcessor/src/main/java/org/jevis/jedataprocessor/Launcher.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/alignment/PeriodAlignmentStep.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/data/CleanDataObject.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/data/CleanDataObjectJEVis.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/data/CleanDataObjectOffline.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/data/ResourceManager.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/differential/DifferentialStep.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/functional/avg/AverageStep.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/functional/sum/SummationStep.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/gap/FillGapStep.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/install/ProcessPatchBuildAllClasses.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/limits/LimitsStep.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/save/ImportStep.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/scaling/ScalingStep.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/workflow/PrepareStep.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/workflow/ProcessManager.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/workflow/ProcessManagerFactory.java, JEDataProcessor/src/test/java/DataRowChecker.java
=> fixed duration millis error in data processor

DataCollector/FTP-Driver/pom.xml, DataCollector/FTP-Driver/src/main/java/org/jevis/ftpdatasource/FTPDataSource.java, DataCollector/HTTP-Driver/src/main/java/org/jevis/httpdatasource/JEVisHTTPDataSource.java, DataCollector/JEDataCollector/src/main/java/org/jevis/jedatacollector/Launcher.java, DataCollector/SOAP-Driver/pom.xml, DataCollector/SOAP-Driver/src/main/java/org/jevis/soapdatasource/JEVisSOAPDataSource.java, DataCollector/sFTP-Driver/pom.xml, DataCollector/sFTP-Driver/src/main/java/org/jevis/sftpdatasource/sFTPDataSource.java, JECalc/src/main/java/org/jevis/jecalc/CalcLauncher.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/Launcher.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/functional/aggregation/Aggregator.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/functional/avg/AverageStep.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/functional/sum/SummationStep.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/save/ImportStep.java, JEReport/src/main/java/org/jevis/report3/ReportLauncher.java, JEStatus/src/main/java/org/jevis/jestatus/AlarmHandler.java
fixed null pointer in jecalc
fixed error in jedatacollector, removed casts
=> fixed api error in data sources

JEStatus/pom.xml, JEStatus/src/main/java/org/jevis/jestatus/AlarmHandler.java, JEStatus/src/main/java/org/jevis/jestatus/Config.java
migrating from apache commons to javax.mail
starttls and ssl needs testing, w/o auth working
removed unnecessary dependencies
=> fixed errors in jestatus

JEAPI-WS/src/main/java/org/jevis/jeapi/ws/JEVisObjectWS.java, JECalc/src/main/java/org/jevis/jecalc/CalcLauncher.java, JECommons/src/main/java/org/jevis/commons/task/CommonTask.java, JEReport/src/main/java/org/jevis/report3/data/report/ReportExecutor.java, JEStatus/src/main/java/org/jevis/jestatus/AlarmHandler.java, Notifier/Notifier-EP/src/main/java/org/jevis/jenotifier/notifier/Email/EmailNotificationDriver.java
updated email notification driver for no auth
=> fixed error in jecalc

JEAPI-WS/src/main/java/org/jevis/jeapi/ws/JEVisDataSourceWS.java, JECommons/src/main/java/org/jevis/commons/utils/Optimization.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/Launcher.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/workflow/ProcessManager.java
fixed null pointer in dataprocessor
=> fixed missing optimization output for clearCache function

JEAPI-WS/pom.xml, JEAPI-WS/src/main/java/org/jevis/jeapi/ws/JEVisDataSourceWS.java, JEVisControlCenter/src/main/jnlp/template.vm, pom.xml
Call garbage collecton after calling the clearCache function.
=> Set the garbage collector to G1 for the webstart.

JEAPI-WS/pom.xml, JEAPI-WS/src/main/java/org/jevis/jeapi/ws/Info.java, JECommons/pom.xml, JECommons/src/main/java/org/jevis/commons/application/Info.java, JECommons/src/main/java/org/jevis/commons/unit/ChartUnits/QuantityUnits.java, JEVisControlCenter/pom.xml, JEVisControlCenter/src/main/java/org/jevis/jeconfig/JEConfig.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartDataModel.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartElements/Note.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartElements/XYChartSerie.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartElements/XYLogicalChartSerie.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/LogicalChart.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/graph/view/ChartView.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/graph/view/GraphPluginView.java, pom.xml
JECC - Diagramme - Wenn L2 und L1 "gerissen" werden soll "L2" im Marker stehen statt "!" #654
=> Fixed null pointer in JEStatus, small changes to logic

JECommons/src/main/java/org/jevis/commons/dataprocessing/CleanDataObject.java, JEStatus/src/main/java/org/jevis/jestatus/DataServerTable.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/attribute/TimeStampEditor.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/extension/CleanDataExtension.java
fixed null pointer in JEStatus
=> JECC - Clean Data Extension - Time Stamp is not saved properly #695

JEAlarm/src/main/java/org/jevis/jealarm/AlarmProcess.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/attribute/AlarmEditor.java
=> fixed order in alarming

JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/Dashboard/datahandler/DataModelDataHandler.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/Dashboard/timeframe/TimeFrames.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/Dashboard/timeframe/ToolBarIntervalSelector.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/Dashboard/widget/PieWidget.java
=> Fixes #851 , Workday support.

JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/Dashboard/config/DashBordModel.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/sample/tableview/SampleTable.java, JEVisControlCenter/src/main/resources/JEVisCC_de.properties, JEVisControlCenter/src/main/resources/JEVisCC_en.properties
Add an error message if the dashboard config file could ne be loaded.
=> Fixes #622 , Number will now be compared as double.

JECommons/src/main/java/org/jevis/commons/calculation/CalcJobFactory.java
Removed sql query debug functions.
=> Fixes #743 , delete all sample will now update attributes.

DataCollector/JEDataCollector/src/main/java/org/jevis/jedatacollector/Launcher.java, JEAlarm/src/main/java/org/jevis/jealarm/Launcher.java, JECalc/src/main/java/org/jevis/jecalc/CalcLauncher.java, JECommons/src/main/java/org/jevis/commons/cli/AbstractCliApp.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/Launcher.java, JEReport/src/main/java/org/jevis/report3/ReportLauncher.java, JEStatus/pom.xml, JEStatus/src/main/java/org/jevis/jestatus/AlarmHandler.java, JEStatus/src/main/java/org/jevis/jestatus/CalculationTable.java, JEStatus/src/main/java/org/jevis/jestatus/CleanDataTable.java, JEStatus/src/main/java/org/jevis/jestatus/DataServerTable.java, JEStatus/src/main/java/org/jevis/jestatus/Launcher.java, JEStatus/src/main/java/org/jevis/jestatus/ServiceStati.java, Notifier/JENotifier/src/main/java/org/jevis/jenotifier/mode/SendNotification.java, Notifier/Notifier-EP/src/main/java/org/jevis/jenotifier/notifier/AppPush/PushNotificationDriver.java, Notifier/Notifier-EP/src/main/java/org/jevis/jenotifier/notifier/Email/EmailNotificationDriver.java, Notifier/Notifier-EP/src/main/java/org/jevis/jenotifier/notifier/Email/EmailServiceProperty.java, Notifier/Notifier-EP/src/main/java/org/jevis/jenotifier/notifier/SQL/SQLNotificationDriver.java, Notifier/Notifier-EP/src/main/java/org/jevis/jenotifier/notifier/VIDA350/VIDA350NotificationDriver.java, Notifier/Notifier/src/main/java/org/jevis/jenotifier/notifier/NotificationDriver.java, var/classes/E-Mail Notification.json, var/classes/JEAlarm.json, var/classes/JECalc.json, var/classes/JEDataCollector.json, var/classes/JEDataProcessor.json, var/classes/JEReport.json, var/classes/JEStatus.json
JEStatus finished stati implementation
=> JEVis Watchdog fixes #568

JEStatus/src/main/java/org/jevis/jestatus/CalculationTable.java, JEStatus/src/main/java/org/jevis/jestatus/CleanDataTable.java, JEStatus/src/main/java/org/jevis/jestatus/DataServerTable.java, JEStatus/src/main/java/org/jevis/jestatus/ServiceStati.java, var/i18n/JEAlarm.json, var/i18n/JECalc.json, var/i18n/JEDataProcessor.json, var/i18n/JEReport.json, var/i18n/JEStatus.json
JEStatus - fixed wrong date format for contact times
Translation - added translation for JEDataProcessor
Translation - updated/fixed/added translation for jealarm, jecalc, jedatacollector, jereport and jestatus
=> JEStatus - fixed inverse definition of date values

JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartPluginElements/TableTopDatePicker.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/BarChart.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/BubbleChart.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/Chart.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/ColumnChart.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/PieChart.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/TableChart.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/XYChart.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/data/GraphDataModel.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/dialog/LoadAnalysisDialog.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/graph/view/GraphPluginView.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/graph/view/ToolBarView.java, JEVisControlCenter/src/main/resources/JEVisCC_de.properties, JEVisControlCenter/src/main/resources/JEVisCC_en.properties
JECC - Charts - Load Analysis Dialog - loosing of calendar cell factory while reloading dialog content fixes #940
JECC - Charts - Table Chart - not working properly fixes #941
=> JECC - Analysen - Der "Play"-Knopf hat kein Mouse-Over-Text fixes #937

JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/jevistree/TreeHelper.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/dialog/ReportWizardDialog.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/tool/PasswordDialog.java
JECC - fixed delete on cancel in confirmation dialog
JECC - Report Wizard Dialog - added multi-select option
=> JECC - fixed password dialog for admin

JEVisControlCenter/pom.xml, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/jevistree/JEVisTreeFactory.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/jevistree/TreeHelper.java, JEVisControlCenter/src/main/resources/JEVisCC_de.properties, JEVisControlCenter/src/main/resources/JEVisCC_en.properties
JECC - added expert functionality for recursive deletion of raw & clean data
=> JECC - increased pom version

JEDataProcessor/src/main/java/org/jevis/jedataprocessor/limits/LimitsStep.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/util/GapsAndLimits.java
JEDataProcessor - fixed null pointer in substitution calculation
=> JEDataProcessor - fixed null pointer in limits step

JEVisControlCenter/src/main/java/org/jevis/jeconfig/JEConfig.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/XYChart.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/data/GraphDataModel.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/statusbar/Statusbar.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/dialog/LoadAnalysisDialog.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/DashBoardPane.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/DashBoardToolbar.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/DashboardControl.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/config2/ConfigManager.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/config2/WidgetPojo.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/datahandler/DataModelDataHandler.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/timeframe/LastPeriod.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/timeframe/TimeFrames.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/widget/ChartWidget.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/widget/LinkerWidget.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/widget/TableWidget.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/widget/ValueWidget.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/widget/Widget.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/graph/view/GraphPluginView.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/tool/DragResizeMod.java, JEVisControlCenter/src/main/resources/JEVisCC_de.properties, JEVisControlCenter/src/main/resources/JEVisCC_en.properties
Add an central loading progression function to the statusbar.
Fixed an bug where the static TimeFrame would not be found in an existing Dashboard.
Fixed an bug where drag & drop would miscalculate because of the widget shadow.
=> Fixed an bug where the loading dialog was empty.

JEAPI-WS/src/main/java/org/jevis/jeapi/ws/JEVisClassWS.java, JEAPI-WS/src/main/java/org/jevis/jeapi/ws/JEVisDataSourceWS.java, JEAPI-WS/src/main/java/org/jevis/jeapi/ws/JEVisObjectWS.java, JECommons/src/main/java/org/jevis/commons/driver/JEVisImporter.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/jevistree/TreeHelper.java
JEAPI-WS - fixed some relationship concurrent modification stuff
JECC - added timeframe to delete tool for clean/raw data
=> JEDataCollector - fixed some problem with timezones

JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/common/GraphAnalysisLinker.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/config2/Limit.java
=> Fixed LinkWidget.

JECommons/src/main/java/org/jevis/commons/utils/Samples.java, JEWebService/src/main/java/org/jevis/rest/Main.java, JEWebService/src/main/java/org/jevis/rest/ResourceAttribute.java, JEWebService/src/main/java/org/jevis/rest/ResourceObject.java, JEWebService/src/main/java/org/jevis/rest/ResourceSample.java, JEWebService/src/main/java/org/jevis/ws/sql/SQLDataSource.java, JEWebService/src/main/java/org/jevis/ws/sql/tables/SampleTable.java
Removed evnentlog cleanup from server start.
=> Event logging fix.

DataCollector/FTP-Driver/src/main/java/org/jevis/ftpdatasource/FTPDataSource.java, DataCollector/HTTP-Driver/src/main/java/org/jevis/httpdatasource/HTTPDataSource.java, DataCollector/SOAP-Driver/src/main/java/org/jevis/soapdatasource/SOAPDataSource.java
Forecast Data - added all option for reference period
Forecast Data - added description and translation
=> JEDataProcessor - improved sample cache loading for forecast data

JEDataProcessor/src/main/java/org/jevis/jedataprocessor/workflow/PrepareStep.java, JEReport/src/main/java/org/jevis/report3/data/reportlink/AlarmFunction.java
JEDataProcessor - fixed start intervals for aggregation
=> JEReport - fixed null pointer in alarm function

JECommons/src/main/java/org/jevis/commons/chart/ChartDataModel.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/XYChart.java, JEVisControlCenter/src/main/resources/styles/charts.css
JECC - Charts - XYChart - changed plot background to white
=> JECC - Diagramme - Summen Funktion hat verschiedene Fehler fixes #1353

JEAlarm/src/main/java/org/jevis/jealarm/AlarmProcess.java, JEAlarm/src/main/java/org/jevis/jealarm/AlarmTable.java, JECommons/src/main/java/org/jevis/commons/alarm/Alarm.java, JECommons/src/main/java/org/jevis/commons/alarm/CleanDataAlarm.java, JECommons/src/main/java/org/jevis/commons/json/JsonAlarm.java, JEReport/src/main/java/org/jevis/report3/data/reportlink/AlarmFunction.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/alarms/AlarmPlugin.java
JECC - Alarm Plugin - adding column for operator fixes #1499
JECC - Alarm Plugin - translation key for L1 alarms is not working fixes #1500
=> JEAlarm - selected setting doesnt seem to work properly fixes #1498

JEAPI-WS/src/main/java/org/jevis/jeapi/ws/JEVisDataSourceWS.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/DashBoardPane.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/DashBoardToolbar.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/DashBordPlugIn.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/DashboardControl.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/config2/WidgetNavigator.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/timeframe/ToolBarIntervalSelector.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/widget/ChartWidget.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/widget/PieWidget.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/layout/LayoutmanagerPlugin.java
Fixed the Dashboard zomm level list view.
=> Fixes #1515,#1581 hotfix

JEVisControlCenter/pom.xml, JEVisControlCenter/src/main/java/org/jevis/jeconfig/tool/PatchNotesPage.java
=> JECC - increased version

JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartElements/BarChartSerie.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartElements/ColumnChartSerie.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartElements/TableSerie.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartElements/XYChartSerie.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartElements/XYLogicalChartSerie.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/BarChart.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/HeatMapChart.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/PieChart.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/XYChart.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/charts/GraphPluginView.java
JECC - BarChartSerie, ColumnChartSerie, TableSerie, XYChartSerie - fixed status bar messaging
JECC - HeatMapChart - added logging for better debugging
JECC - Charts - improved data model logice
=> JECC - Charts - Logical chart fixed errors with new data model

DataCollector/CSV-Driver/src/main/java/org/jevis/csvparser/CSVParser.java, DataCollector/CSV-Driver/src/main/java/org/jevis/csvparser/JEVisCSVParser.java, DataCollector/CSV-Driver/src/main/java/org/jevis/csvparser/LineError.java, DataCollector/JEDataCollector/src/main/java/org/jevis/jedatacollector/Launcher.java, JEAlarm/src/main/java/org/jevis/jealarm/Launcher.java, JECalc/src/main/java/org/jevis/jecalc/CalcLauncher.java, JECommons/src/main/java/org/jevis/commons/DatabaseHelper.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/Launcher.java, JEReport/src/main/java/org/jevis/report3/ReportLauncher.java, JEStatus/src/main/java/org/jevis/jestatus/Launcher.java
JEDataCollector - JEVisCSVParser - fixed some strange row/column logic
JECommons - DatabaseHelper - fixed some null pointers
Launcher - fixed second preload on run
=> JEDataCollector - JEVisCSVParser - fixed some null pointers

JEVisControlCenter/pom.xml, JEVisControlCenter/src/main/java/org/jevis/jeconfig/tool/PatchNotesPage.java
=> JECC - patch notes

DataCollector/FTP-Driver/src/main/java/org/jevis/ftpdatasource/FTPDataSource.java, JECommons/src/main/java/org/jevis/commons/DatabaseHelper.java
JECommons - DatabaseHelper - fixed null pointer
=> JEDataCollector - FTPDataSource - fixed null pointer

JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartElements/XYChartSerie.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/XYChart.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/data/ChartDataRow.java
JECC - Charts - sum function fix
JECC - Charts - allow empty data rows for selection
=> JECC - Charts - fixed asynchronous period visualization

JEVisControlCenter/pom.xml, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartElements/CustomMarkerRenderer.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartElements/MultiChartZoomer.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/charts/GraphPluginView.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/sample/SampleGraphExtension.java
JECC - Charts - axis labels are cut off fixes #1687
JECC - Charts - x axis is not scaling properly in rare cases fixes #1688
=> JECC - SampleGraphExtension - look like analysis chart fixes #1689

JEAlarm/src/main/java/org/jevis/jealarm/AlarmProcess.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/data/ChartDataRow.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/alarms/AlarmPlugin.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/widget/ChartWidget.java
JECC - AlarmPlugin - fixed some errors with localization of special characters
=> JECC - Dashboard - ChartWidget - fixed size error

JEVisControlCenter/src/main/java/org/jevis/jeconfig/JEConfig.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/dialog/ImageViewerDialog.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/meters/AttributeValueChange.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/meters/MeterPlugin.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/tool/Layouts.java
JECC - Add additonal check for the last user path.
=> JECC - MeterPlugin  - Fixed an bug when the file upload did not work.

JEVisControlCenter/src/main/java/org/jevis/jeconfig/PluginManager.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/meters/JEVisClassTab.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/meters/MeterPlugin.java
JECC - MeterPlugin - removed loading on program startup
=> JECC - MeterPlugin - added loading to standard thread pool

JEVisControlCenter/pom.xml, JEVisControlCenter/src/main/java/org/jevis/jeconfig/tool/PatchNotesPage.java
=> JECC - PatchNotesPage - added new commits

JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/control/DayBox.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/control/MonthBox.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/dialog/EnterDataDialog.java
JECC - EnterDataDialog - fixed some layout issues
=> JECC - EnterDataDialog - fixed some current date issues

JEVisControlCenter/pom.xml, JEVisControlCenter/src/main/java/org/jevis/jeconfig/tool/PatchNotesPage.java
=> JECC - PatchNotesPage - new commits

JEVisControlCenter/pom.xml, JEVisControlCenter/src/main/java/org/jevis/jeconfig/tool/PatchNotesPage.java
=> JECC - PatchNotesPage - updated

JEReport/src/main/java/org/jevis/report3/data/report/periodic/PeriodPrecondition.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/jevistree/TreeHelper.java, JEWebService/pom.xml, Notifier/Notifier-EP/src/main/java/org/jevis/jenotifier/notifier/Email/EmailNotification.java
Notifier-EP - EmailNotification - changed email validation
=> JEReport - fixed problem with event precondition

.idea/encodings.xml, DataCollector/envidatec-vida/pom.xml, DataCollector/envidatec-vida/src/main/java/org/jevis/vida350datasource/VIDA350DataSource.java, DataCollector/loytec-xml-dl/pom.xml, DataCollector/loytec-xml-dl/src/main/java/org/jevis/loytecxmldl/LoytecXmlDlDataSource.java, DataCollector/loytec-xml-dl/src/main/java/org/jevis/loytecxmldl/jevis/Helper.java, DataCollector/loytec-xml-dl/src/main/java/org/jevis/loytecxmldl/jevis/LoytecXmlDlChannel.java, DataCollector/loytec-xml-dl/src/main/java/org/jevis/loytecxmldl/jevis/LoytecXmlDlChannelClass.java, DataCollector/loytec-xml-dl/src/main/java/org/jevis/loytecxmldl/jevis/LoytecXmlDlChannelDirectory.java, DataCollector/loytec-xml-dl/src/main/java/org/jevis/loytecxmldl/jevis/LoytecXmlDlChannelDirectoryClass.java, DataCollector/loytec-xml-dl/src/main/java/org/jevis/loytecxmldl/jevis/LoytecXmlDlGenericChannelDirectoryClass.java, DataCollector/loytec-xml-dl/src/main/java/org/jevis/loytecxmldl/jevis/LoytecXmlDlParser.java, DataCollector/loytec-xml-dl/src/main/java/org/jevis/loytecxmldl/jevis/LoytecXmlDlServer.java, DataCollector/loytec-xml-dl/src/main/java/org/jevis/loytecxmldl/jevis/LoytecXmlDlServerClass.java, DataCollector/loytec-xml-dl/src/main/java/org/jevis/loytecxmldl/jevis/LoytecXmlDlSoapRequestTemplate.java, DataCollector/loytec-xml-dl/src/main/java/org/jevis/loytecxmldl/jevis/LoytecXmlDlSpecializedChannelDirectory.java, DataCollector/loytec-xml-dl/src/main/java/org/jevis/loytecxmldl/jevis/LoytecXmlDlSpecializedChannelDirectoryClass.java, DataCollector/pom.xml
DataCollector - added vida350 driver
=> DataCollector - added LoytecXmlDl driver

DataCollector/CSV-Driver/src/main/java/org/jevis/csvparser/CSVParser.java, DataCollector/CSV-Driver/src/main/java/org/jevis/csvparser/DataPoint.java, DataCollector/CSV-Driver/src/main/java/org/jevis/csvparser/JEVisCSVParser.java, DataCollector/XML-Driver/src/main/java/org/jevis/xmlparser/DataPoint.java, DataCollector/XML-Driver/src/main/java/org/jevis/xmlparser/JEVisXMLParser.java, DataCollector/XML-Driver/src/main/java/org/jevis/xmlparser/XMLParser.java, DataCollector/envidatec-vida/src/main/java/org/jevis/vida350datasource/VIDA350DataSource.java, DataCollector/loytec-xml-dl/src/main/java/org/jevis/loytecxmldl/LoytecXmlDlDataSource.java, DataCollector/loytec-xml-dl/src/main/java/org/jevis/loytecxmldl/jevis/LoytecXmlDlChannel.java, DataCollector/loytec-xml-dl/src/main/java/org/jevis/loytecxmldl/jevis/LoytecXmlDlChannelClass.java, DataCollector/loytec-xml-dl/src/main/java/org/jevis/loytecxmldl/jevis/LoytecXmlDlParser.java, JECommons/src/main/java/org/jevis/commons/driver/JEVisImporter.java, JECommons/src/main/java/org/jevis/commons/driver/Result.java
JECommons - JEVisImporter - changed to target string to support different attributes
=> DataCollector - CSVParser - fixed column parsing

.idea/encodings.xml, JEAPI-WS/src/main/java/org/jevis/jeapi/ws/HTTPConnection.java, JEAPI-WS/src/main/java/org/jevis/jeapi/ws/JEVisDataSourceWS.java, JECommons/src/main/java/org/jevis/commons/ws/sql/Config.java
- Removed unnecessary webservice call in jecc version check.
=> - Set retries to 3.

JEVisControlCenter/src/main/java/org/jevis/jeconfig/Constants.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/JEConfig.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/TopMenu.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/jevistree/JEVisTreeFactory.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/jevistree/TreeHelper.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/ObjectPlugin.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/tool/Exceptions.java
Add an basic Error Dialog to JEConfig main.
=> Fixes #1945 - JECC - Not all menu entry's are working

JEAlarm/src/main/java/org/jevis/jealarm/AlarmProcess.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/jevistree/TreeHelper.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/jevistree/filter/BasicCellFilter.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/dialog/SelectTargetDialog.java
JECC - SelectTargetDialog - added base data to data filters
JECC - CalculationExtension - fixed problem with stacked clean data objects
=> JEAlarm - fixed some problem with null tolerance

JECommons/src/main/java/org/jevis/commons/datetime/PeriodHelper.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartElements/XYChartSerie.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartPluginElements/DataPointTableViewPointer.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/XYChart.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/data/ChartDataRow.java
JECC - Charts - improved date formatting
=> JECC - Charts - fixed some null pointer in DataPointTableViewPointer

DataCollector/Email-Driver/pom.xml, DataCollector/Email-Driver/src/main/java/org/jevis/emaildatasource/DBHelper.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/PluginManager.java, var/classes/EMail Channel.json, var/i18n/IMAPEMailServer.json, var/i18n/POP3EMailServer.json
Classes - EMail Channel.json - added missing attributes
=> JECC - PluginManager - added fallback for no configured plugins

DataCollector/OPCUA-Driver/pom.xml, DataCollector/OPCUA-Driver/src/main/java/org/jevis/jeopc/OPCClient.java, DataCollector/OPCUA-Driver/src/main/java/org/jevis/jeopc/OPCUADataSource.java, DataCollector/OPCUA-Driver/src/main/java/org/jevis/jeopc/OPCUAServer.java
Changed parent project to datacollector.
=> Fixed an bug where the user name was not used for OPC.

JEVisControlCenter/pom.xml, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/statusbar/Statusbar.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/DashboardControl.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/widget/ValueWidget.java
Fixed #2103 - JECC - Dashboard - Duplicate Loading at Startup
=> Fixed duplicate pom entry for opc.

JECommons/src/main/java/org/jevis/commons/dataprocessing/CleanDataObject.java, JECommons/src/main/java/org/jevis/commons/dataprocessing/processor/preparation/PrepareStep.java, JECommons/src/main/java/org/jevis/commons/datetime/PeriodHelper.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartPluginElements/DataPointTableViewPointer.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/XYChart.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/data/ChartDataRow.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/accounting/AccountingPlugin.java
JECC - DataPointTableViewPointer - fixed event performance
JECC - Charts - XYChart - fixed mouse moved performance
=> JEDataProcessor - fixed recurring sample error for 15->1

JEVisControlCenter/pom.xml, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/accounting/AccountingPlugin.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dtrc/OutputView.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/tool/PatchNotesPage.java
=> JECC - PatchNotesPage - added commits

JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/accounting/AccountingPlugin.java, var/classes/Gas Supply Contractor.json, var/i18n/GasSupplyContractor.json
Classes - Gas Supply Contractor - added heating value
Classes - Gas Supply Contractor - state number
=> JECC - AccountingPlugin - fixed save

JEVisControlCenter/pom.xml, JEVisControlCenter/src/main/java/org/jevis/jeconfig/tool/PatchNotesPage.java
=> JECC - PatchNotesPage - updated commits

JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/accounting/AccountingTemplateHandler.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dtrc/OutputView.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dtrc/TemplateHandler.java
JECC - TRCPlugin - improved combo box content structure
JECC - TRCPlugin - saving doesn't respect selected name
JECC - TRCPlugin - changed variable name for ungrouped objects combo box label
JECC - AccountingPlugin - saving doesn't respect selected name
=> JECC - TRCPlugin - problem with multiple ungrouped objects of same class

JECommons/src/main/java/org/jevis/commons/DatabaseHelper.java, JECommons/src/main/java/org/jevis/commons/alarm/AlarmTable.java, JECommons/src/main/java/org/jevis/commons/alarm/CleanDataAlarm.java, JECommons/src/main/java/org/jevis/commons/dataprocessing/BasicProcess.java, JECommons/src/main/java/org/jevis/commons/dataprocessing/CleanDataObject.java, JECommons/src/main/java/org/jevis/commons/dataprocessing/ForecastDataObject.java, JECommons/src/main/java/org/jevis/commons/dataprocessing/MathDataObject.java, JECommons/src/main/java/org/jevis/commons/dataprocessing/ProcessOptions.java, JECommons/src/main/java/org/jevis/commons/dataprocessing/processor/steps/ImportStep.java, JECommons/src/main/java/org/jevis/commons/driver/DataSource.java, JECommons/src/main/java/org/jevis/commons/utils/CommonMethods.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartElements/BarChartSerie.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartElements/BubbleChartSerie.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartElements/TableSerie.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartElements/XYChartSerie.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartPluginElements/DataPointNoteDialog.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartPluginElements/DataPointTableViewPointer.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/BarChart.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/XYChart.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/data/ChartDataRow.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/control/YearBox.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/jevistree/TreeHelper.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/jevistree/dialog/NewObject.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/jevistree/methods/CommonMethods.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/datahandler/DataModelDataHandler.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dtrc/TemplateInput.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/attribute/PeriodEditor.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/attribute/TimeStampEditor.java
JECC - ChartPlugin - ChartDataRow - added enabled check
=> JECommons - changed first timestamp from 2001 to 1990

JEVisControlCenter/pom.xml, JEVisControlCenter/src/main/java/org/jevis/jeconfig/tool/PatchNotesPage.java
=> JECC - added new commits

JECommons/src/main/java/org/jevis/commons/dataprocessing/MathDataObject.java, JECommons/src/main/java/org/jevis/commons/dataprocessing/processor/preparation/PrepareStep.java, JECommons/src/main/java/org/jevis/commons/dataprocessing/processor/steps/DifferentialStep.java, JECommons/src/main/java/org/jevis/commons/dataprocessing/processor/steps/MathStep.java
JEDataProcessor - fixed some problems with monthly & yearly aggregation
=> JEDataProcessor - MathDataObject - fixed some null pointer

JEAlarm/src/main/java/org/jevis/jealarm/AlarmProcess.java
JEAlarm - AlarmProcess - improved null pointer handling for async data
=> JEAlarm - AlarmProcess - now supports only l2 step configurations

JEVisControlCenter/pom.xml, JEVisControlCenter/src/main/java/org/jevis/jeconfig/tool/PatchNotesPage.java
=> JECC - updated patch notes pages

.gitignore, JECommons/src/main/java/org/jevis/commons/cli/ConnectionEncoder.java, JECommons/src/main/java/org/jevis/commons/config/CommonOptions.java, JECommons/src/main/java/org/jevis/commons/ws/sql/Config.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/login/FXLogin.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/dialog/TemplateCalculationInputDialog.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/accounting/AccountingPlugin.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dtrc/IntervalSelector.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dtrc/OutputView.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dtrc/TRCPlugin.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dtrc/TemplateInput.java, JEWebService/src/main/java/org/jevis/rest/ResourceJavaVersion.java, JEWebService/src/main/java/org/jevis/rest/ResourceSample.java
JECC - FXLogin - added language boot option
JECC - AccountingPlugin - added input fallback with zero
JECC - AccountingPlugin - fixed xlsx output for null uni
JECC - AccountingPlugin - fixed input labeling for ungrouped inputs
JEWebService - get jecc version from compiled path
JEWebService - added jecc distribution method
JEWebService - added runtime distribution method
=> JECC - Config - added boot to plugin

JEVisControlCenter/src/main/java/org/jevis/jeconfig/dialog/LoadAnalysisDialog.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/charts/ChartPlugin.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/charts/ToolBarView.java
JECC - ChartPlugin - disabled overlay close on load analysis dialog
=> JECC - ChartPlugin - fixed disabled quick selection box

JECommons/src/main/java/org/jevis/commons/calculation/CalcInputObject.java, JECommons/src/main/java/org/jevis/commons/dataprocessing/function/InputFunction.java, JECommons/src/main/java/org/jevis/commons/dataprocessing/processor/workflow/ResourceManager.java, JECommons/src/main/java/org/jevis/commons/ws/json/JsonAttribute.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartPluginElements/Columns/ChartPluginColumn.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartPluginElements/PickerCombo.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartSettings.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/XYChart.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/data/AnalysisDataModel.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/charts/ChartPlugin.java
=> JECommons - Calculation - fixed user data input

JEVisControlCenter/pom.xml, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/widget/ValueEditWidget.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dtrc/OutputView.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/tool/PatchNotesPage.java
JECC - increased version
JECC - PachtNotesPage - added new commits
=> JECC - Dialog - EnterDataDialog - fixed opening

JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/BubbleChart.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/XYChart.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/charts/ChartPlugin.java
JECC - ChartPlugin - fixed problem when directly jumping from dashboard to chart plugin
=> JECC - ChartPlugin - fixed secondary yaxis problem

JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartPluginElements/Boxes/AnalysesComboBox.java, JEWebService/src/main/java/org/jevis/rest/ResourceSample.java
JEWebservice - ResourceSample - fixed user exception for files
=> JECC - ChartPlugin - AnalysesComboBox - more checks

JECommons/src/main/java/org/jevis/commons/dataprocessing/function/MathFunction.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/XYChart.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/charts/ChartPlugin.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/config2/WidgetConfigDialog.java
JECC - DashboardPlugin - enabled table menu for aggregation/manipulation columns
=> JECommons - MathFunction - fixed missing values for avg with aggregation

JEVisControlCenter/src/main/java/org/jevis/jeconfig/dialog/EnterDataDialog.java, JEWebService/src/main/java/org/jevis/rest/ResourceSample.java
JEWebService - ResourceSample - fixed wrong read file check
=> JECC - EnterDataDialog - fixed period check for differential raw values

JECommons/src/main/java/org/jevis/commons/unit/ChartUnits/ChartUnits.java, JECommons/src/main/java/org/jevis/commons/unit/ChartUnits/QuantityUnits.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartPluginElements/Boxes/ChartUnitBox.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/attribute/RangingValueEditor.java
JECC - ChartPlugin - added mass flow units
JECC - ChartPlugin - fixed some unit selection bug JECC - ObjectPlugin - fixed some null pointer in RangingValueEditor
=> JECC - ChartPlugin - added default unit

JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartPluginElements/Boxes/ValueWithDateTimeBox.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/XYChart.java
JECC - ChartPlugin - fixed min max calculation for stacked header entries
=> JECC - ChartPlugin - fixed double.max values appearing in header table

DataCollector/pom.xml, JECommons/src/main/resources/JEVis_ar.properties, JECommons/src/main/resources/JEVis_de.properties, JECommons/src/main/resources/JEVis_en.properties, JECommons/src/main/resources/JEVis_ru.properties, JECommons/src/main/resources/JEVis_th.properties, JECommons/src/main/resources/JEVis_uk.properties, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/XYChart.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/data/ChartDataRow.java
JECC - ChartPlugin - stacked charts changed sum description
=> JECC - ChartPlugin - stacked charts added period

JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dtrc/OutputView.java
JECC - TRCPlugin - fixed time dependent value generation for formulas
=> JECC - TRCPlugin - integration of ranging values

JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dtrc/OutputView.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/extension/RoleExtention.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/object/extension/role/Membership.java
JECC - ObjectPlugin - RoleExtention - improved path display for groups
=> JECC - TRCPlugin - fixed sort order for outputs

JEVisControlCenter/src/main/java/org/jevis/jeconfig/dialog/EnterDataDialog.java
JECC - ObjectPlugin - EnterDataDialog - added missing translations
=> JECC - ObjectPlugin - EnterDataDialog - improved size

JECommons/src/main/java/org/jevis/commons/alarm/CleanDataAlarm.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/XYChart.java
JECC - ChartPlugin - improved min/max axis value finding
=> JEAlarm - fixed wrong alarm configuration used in some cases

JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/action/data/NPVData.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/action/data/NPVYearData.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/action/ui/ActionTab.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/action/ui/ActionTable.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/action/ui/ActionToolbar.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/action/ui/TableSumPanel.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/action/ui/tab/CapitalTab.java
=> Action Bugfix

DataCollector/JEDataCollector/src/main/java/org/jevis/jedatacollector/Launcher.java, JECalc/src/main/java/org/jevis/jecalc/CalcLauncher.java, JEDataProcessor/src/main/java/org/jevis/jedataprocessor/Launcher.java
JECalc - Launcher - show current jobs
JEDataCollector - Launcher - show current jobs
=> JEDataProcessor - Launcher - show current jobs

JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/Charts/BubbleChart.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/data/RowNote.java
JECC - DashboardPlugin - TimeFrameWidget - fixed javafx threading JECC - DashboardPlugin - TimeFrameWidget - fixed null pointer
=> JECC - ChartPlugin - TableChartV - added setting for column/row sums

DataCollector/JSONParser/src/main/java/org/jevis/jsonparser/JEVisJSONParser.java, DataCollector/JSONParser/src/main/java/org/jevis/jsonparser/JSONParser.java
DataCollector - JSONParser - adde logger messages
=> DataCollector - JSONParser - removed system.outs

JEStatus/src/main/java/org/jevis/jestatus/DataServerTable.java, JEStatus/src/main/java/org/jevis/jestatus/StatusHandler.java, Notifier/Notifier-EP/src/main/java/org/jevis/jenotifier/notifier/Email/EmailNotification.java, Notifier/Notifier-EP/src/main/java/org/jevis/jenotifier/notifier/Email/EmailNotificationDriver.java
Nofier-EP - added priority option
=> JEStatus - added priority tag to not empty status mails

JECommons/src/main/resources/JEVis_en.properties, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/charts/ToolBarFunctions.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/widget/NetGraphWidget.java
JECC - DashboardPlugin - NetGraphWidget -fixed null pointer
=> JECC - ChartPlugin - fixed missing translation

JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartPluginElements/SelectionTable/UnitTableCell.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartPluginElements/tabs/ChartTab.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/dialog/ImageViewerDialog.java
JECC - ImageViewerDialog - fixed scaling
=> JECC - ChartPlugin - added for all button for units

JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartPluginElements/TreeSelectionDialog.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartPluginElements/tabs/ChartTab.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/application/Chart/ChartPluginElements/tree/JEVisTreeView.java, JEVisControlCenter/src/main/java/org/jevis/jeconfig/plugin/dashboard/config2/WidgetConfigDialog.java
JECC - JEVisTreeView - fixed expanding tree on searching
=> JECC - Dashboard Plugin - removed uneccessary config

DataCollector/XLSX-Driver/pom.xml, DataCollector/XLSX-Driver/src/main/java/org/jevis/xlsxparser/DataPoint.java, DataCollector/XLSX-Driver/src/main/java/org/jevis/xlsxparser/JEVisXLSXParser.java, DataCollector/XLSX-Driver/src/main/java/org/jevis/xlsxparser/XLSXParser.java, var/classes/XLSX Parser.json
DataCollector - XLSX Parser - added column mode
=> DataCollector - XLSX Parser - bugfixes
